# Model evaluation

In [1]:
import pandas as pd
import numpy as np
%matplotlib inline
import matplotlib.pyplot as plt

In [2]:
heart_disease = pd.read_csv("./data/heart-disease.csv")
heart_disease.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2,1
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2,1
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2,1
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2,1


In [3]:
X = heart_disease.drop("target", axis=1)
y = heart_disease["target"]

X.head(), y.head()

(   age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
 0   63    1   3       145   233    1        0      150      0      2.3      0   
 1   37    1   2       130   250    0        1      187      0      3.5      0   
 2   41    0   1       130   204    0        0      172      0      1.4      2   
 3   56    1   1       120   236    0        1      178      0      0.8      2   
 4   57    0   0       120   354    0        1      163      1      0.6      2   
 
    ca  thal  
 0   0     1  
 1   0     2  
 2   0     2  
 3   0     2  
 4   0     2  ,
 0    1
 1    1
 2    1
 3    1
 4    1
 Name: target, dtype: int64)

In [4]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42);
from sklearn.ensemble import RandomForestClassifier
clf = RandomForestClassifier(random_state=42)
clf.fit(X_train, y_train)

RandomForestClassifier(random_state=42)

In [5]:
from sklearn.model_selection import cross_val_score
score = cross_val_score(clf, X, y, cv=5)
score

array([0.81967213, 0.8852459 , 0.83606557, 0.85      , 0.8       ])

In [6]:
mean_accuracy = np.mean(score)
mean_accuracy

np.float64(0.8381967213114756)

In [7]:
print(f"Heart disease classifier cross-validated accuracy: {(np.mean(score) * 100):.2f} %")

Heart disease classifier cross-validated accuracy: 83.82 %


### Area under the receiver operating characteristic curve (ROC / AUC) 
* `Area under curve (AUC)`

* `Receive operating characteristic curve (ROC curve)`

True positive rate vs false positive rate

In [10]:
y_probs = clf.predict_proba(X_test)
len(y_probs)

61

In [16]:
y_probs

array([[0.95, 0.05],
       [0.38, 0.62],
       [0.45, 0.55],
       [0.86, 0.14],
       [0.21, 0.79],
       [0.16, 0.84],
       [0.36, 0.64],
       [0.95, 0.05],
       [0.96, 0.04],
       [0.53, 0.47],
       [0.19, 0.81],
       [0.64, 0.36],
       [0.07, 0.93],
       [0.87, 0.13],
       [0.04, 0.96],
       [0.03, 0.97],
       [0.01, 0.99],
       [0.92, 0.08],
       [0.98, 0.02],
       [0.94, 0.06],
       [0.54, 0.46],
       [0.9 , 0.1 ],
       [0.35, 0.65],
       [0.23, 0.77],
       [0.35, 0.65],
       [0.34, 0.66],
       [0.21, 0.79],
       [0.3 , 0.7 ],
       [0.9 , 0.1 ],
       [0.12, 0.88],
       [0.91, 0.09],
       [0.91, 0.09],
       [0.97, 0.03],
       [0.67, 0.33],
       [0.47, 0.53],
       [0.81, 0.19],
       [0.41, 0.59],
       [0.22, 0.78],
       [0.41, 0.59],
       [0.13, 0.87],
       [0.19, 0.81],
       [0.26, 0.74],
       [0.16, 0.84],
       [0.34, 0.66],
       [0.29, 0.71],
       [0.76, 0.24],
       [0.45, 0.55],
       [0.01,

In [12]:
y_probs_positive = y_probs[:, 1]
y_probs_positive[:10]

array([0.05, 0.62, 0.55, 0.14, 0.79, 0.84, 0.64, 0.05, 0.04, 0.47])

In [17]:
from sklearn.metrics import roc_curve
fpr, tpr, thresholds = roc_curve(y_test, y_probs_positive)
fpr, tpr, thresholds[:10]

(array([0.        , 0.        , 0.        , 0.        , 0.03448276,
        0.03448276, 0.06896552, 0.10344828, 0.10344828, 0.13793103,
        0.13793103, 0.17241379, 0.17241379, 0.20689655, 0.20689655,
        0.24137931, 0.24137931, 0.31034483, 0.4137931 , 0.44827586,
        0.51724138, 0.55172414, 0.65517241, 0.68965517, 0.72413793,
        0.86206897, 1.        ]),
 array([0.     , 0.0625 , 0.28125, 0.40625, 0.4375 , 0.59375, 0.65625,
        0.6875 , 0.71875, 0.71875, 0.78125, 0.8125 , 0.90625, 0.90625,
        0.9375 , 0.9375 , 0.96875, 0.96875, 0.96875, 0.96875, 0.96875,
        0.96875, 0.96875, 1.     , 1.     , 1.     , 1.     ]),
 array([ inf, 0.99, 0.85, 0.81, 0.79, 0.7 , 0.66, 0.65, 0.64, 0.62]))