In [1]:
import numpy as np

In [17]:
a1 = np.array([1, 6, 4])

In [18]:
a1.ndim, a1.shape, a1.size

(1, (3,), 3)

In [19]:
rng = np.random.default_rng(0)
a2 = rng.integers(0, 10, size = (2, 3))
a2

array([[8, 6, 5],
       [2, 3, 0]])

In [20]:
a1 > a2

array([[False, False, False],
       [False,  True,  True]])

In [21]:
a1 >= a2

array([[False,  True, False],
       [False,  True,  True]])

In [22]:
a1 > 1

array([False,  True,  True])

In [23]:
a1 == a2

array([[False,  True, False],
       [False, False, False]])