In [2]:
import pandas as pd
import numpy as np
%matplotlib inline 
import matplotlib.pyplot as plt

# Element wise multiplication or HADAMARD product

In [4]:
rng = np.random.default_rng(0)
a1 = rng.integers(1, 10, size=(5, 3))
a2 = rng.integers(1, 10, size=(5, 3))
a1, a2

(array([[8, 6, 5],
        [3, 3, 1],
        [1, 1, 2],
        [8, 6, 9],
        [5, 6, 9]]),
 array([[7, 6, 5],
        [6, 9, 3],
        [8, 7, 1],
        [4, 8, 5],
        [1, 7, 7]]))

In [5]:
a1 * a2

array([[56, 36, 25],
       [18, 27,  3],
       [ 8,  7,  2],
       [32, 48, 45],
       [ 5, 42, 63]])

# Dot product

In [7]:
np.dot(a1, a2)

ValueError: shapes (5,3) and (5,3) not aligned: 3 (dim 1) != 5 (dim 0)

In [8]:
a1.shape, a2.shape

((5, 3), (5, 3))

In [9]:
transposed_a2 = a2.T

In [10]:
np.dot(a1, transposed_a2)

array([[117, 117, 111, 105,  85],
       [ 44,  48,  46,  41,  31],
       [ 23,  21,  17,  22,  22],
       [137, 129, 115, 125, 113],
       [116, 111,  91, 113, 110]])