In [1]:
import numpy as np

In [10]:
# Arithmetic
a1 = np.array([1,2,4])
a1

array([1, 2, 4])

In [11]:
a1 + 2 

array([3, 4, 6])

In [12]:
a2 = np.random.randint(1, 10, size = (2, 3))
a2

array([[6, 9, 6],
       [7, 1, 8]], dtype=int32)

In [13]:
a2 * 10 

array([[60, 90, 60],
       [70, 10, 80]], dtype=int32)

In [ ]:
a1

array([1, 2, 4])

In [16]:
a2 

array([[6, 9, 6],
       [7, 1, 8]], dtype=int32)

In [17]:
a2 * a1

array([[ 6, 18, 24],
       [ 7,  2, 32]])

In [30]:
rng = np.random.default_rng(0)
a3 = rng.integers(1, 10, (2,3,3))
a3

array([[[8, 6, 5],
        [3, 3, 1],
        [1, 1, 2]],

       [[8, 6, 9],
        [5, 6, 9],
        [7, 6, 5]]])

In [37]:
# Reshape
a2 = np.resize(a2, (3, 3))
a2

array([[6, 9, 6],
       [7, 1, 8],
       [6, 9, 6]], dtype=int32)

In [38]:
a2 * a3

array([[[48, 54, 30],
        [21,  3,  8],
        [ 6,  9, 12]],

       [[48, 54, 54],
        [35,  6, 72],
        [42, 54, 30]]])

In [39]:
# Arithmetic
a1 / a2

array([[0.16666667, 0.22222222, 0.66666667],
       [0.14285714, 2.        , 0.5       ],
       [0.16666667, 0.22222222, 0.66666667]])

In [43]:
a1.dtype

dtype('int64')

In [44]:
a2.dtype 

dtype('int32')

In [46]:
# Floor() or //
a1 // a2

array([[0, 0, 0],
       [0, 2, 0],
       [0, 0, 0]])

In [47]:
a1 ** a2

array([[    1,   512,  4096],
       [    1,     2, 65536],
       [    1,   512,  4096]])

In [48]:
a1 % a2

array([[1, 2, 4],
       [1, 0, 4],
       [1, 2, 4]])

In [49]:
np.mod(a1, a2)

array([[1, 2, 4],
       [1, 0, 4],
       [1, 2, 4]])

In [53]:
# e number ----- exponential
# e ^ 2
np.exp(2)

np.float64(7.38905609893065)

In [54]:
np.exp(a1)

array([ 2.71828183,  7.3890561 , 54.59815003])

In [55]:
# Log ----- ln
np.log(np.e)

np.float64(1.0)