# NumPy Practice

This notebook offers a set of exercises for different tasks with NumPy.

It should be noted there may be more than one different way to answer a question or complete an exercise.

Exercises are based off (and directly taken from) the quick introduction to NumPy notebook.

Different tasks will be detailed by comments or text.

For further reference and resources, it's advised to check out the [NumPy documentation](https://numpy.org/devdocs/user/index.html).

And if you get stuck, try searching for a question in the following format: "how to do XYZ with numpy", where XYZ is the function you want to leverage from NumPy.

In [1]:
# Import NumPy as its abbreviation 'np'
import numpy as np

In [2]:
# Create a 1-dimensional NumPy array using np.array()
a1 = np.array([1, 2, 3])

# Create a 2-dimensional NumPy array using np.array()
a2 = np.array([[1, 2, 3], [4, 5, 6]])

# Create a 3-dimensional Numpy array using np.array()
a3 = np.array([
    [[1 , 2, 3], [4, 5, 6], [7, 8, 9]], 
    [[10, 11, 12], [13, 14, 15], [16, 17, 18]]
])

Now we've you've created 3 different arrays, let's find details about them.

Find the shape, number of dimensions, data type, size and type of each array.

In [3]:
# Attributes of 1-dimensional array (shape, 
# number of dimensions, data type, size and type)
a1.shape, a1.ndim, type(a1), a1.size

((3,), 1, numpy.ndarray, 3)

In [4]:
# Attributes of 2-dimensional array
a2.shape, a2.ndim, type(a2), a2.size

((2, 3), 2, numpy.ndarray, 6)

In [5]:
# Attributes of 3-dimensional array
a3.shape, a3.ndim, type(a3), a3.size

((2, 3, 3), 3, numpy.ndarray, 18)

In [6]:
# Import pandas and create a DataFrame out of one
# of the arrays you've created
import pandas as pd

In [9]:
a3_dataframe = pd.DataFrame(a2, index = ["A", "B"])
a3_dataframe

,0,1,2
A,1,2,3
B,4,5,6


In [11]:
# Create an array of shape (10, 2) with only ones
ones = np.ones((10, 2), dtype = "int")
ones

array([[1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1]])

In [14]:
# Create an array of shape (7, 2, 3) of only zeros
zeros = np.zeros((7, 2, 3), dtype = "float")
zeros, zeros.size

(array([[[0., 0., 0.],
         [0., 0., 0.]],
 
        [[0., 0., 0.],
         [0., 0., 0.]],
 
        [[0., 0., 0.],
         [0., 0., 0.]],
 
        [[0., 0., 0.],
         [0., 0., 0.]],
 
        [[0., 0., 0.],
         [0., 0., 0.]],
 
        [[0., 0., 0.],
         [0., 0., 0.]],
 
        [[0., 0., 0.],
         [0., 0., 0.]]]),
 42)

In [15]:
# Create an array within a range of 0 and 100 with step 3
ranged_ndarray = np.arange(0, 100, 3)
ranged_ndarray

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [17]:
# Create a random array with numbers between 0 and 10 of size (7, 2)
random_ndarray = np.random.randint(0, 10, size = (7, 2))
random_ndarray

array([[8, 8],
       [0, 4],
       [7, 3],
       [2, 9],
       [7, 9],
       [2, 5],
       [0, 3]], dtype=int32)

In [19]:
# Create a random array of floats between 0 & 1 of shape (3, 5)
random_ndarray2 = np.random.uniform(0, 1, (3, 5))
random_ndarray2

array([[0.23199532, 0.39900736, 0.96536065, 0.5409613 , 0.25765393],
       [0.93886057, 0.87534405, 0.81870927, 0.90335697, 0.8436105 ],
       [0.25706867, 0.06212627, 0.16451982, 0.60672943, 0.14104886]])

In [23]:
# Set the random seed to 42
rng = np.random.default_rng(42)

# Create a random array of numbers between 0 & 10 of size (4, 6)
random_ndarray3 = rng.integers(0, 10, size = (4, 6))
random_ndarray3

array([[0, 7, 6, 4, 4, 8],
       [0, 6, 2, 0, 5, 9],
       [7, 7, 7, 7, 5, 1],
       [8, 4, 5, 3, 1, 9]])

Run the cell above again, what happens?

Are the numbers in the array different or the same? Why do think this is?

In [25]:
# Create an array of random numbers between 1 & 10 of size (3, 7)
# and save it to a variable
random_ndarray4 = np.random.randint(1, 10, size = (3, 7))
random_ndarray4

array([[3, 4, 9, 6, 8, 1, 5],
       [8, 1, 1, 2, 6, 1, 5],
       [8, 6, 5, 7, 9, 7, 2]], dtype=int32)

In [27]:
# Find the unique numbers in the array you just created
np.unique(random_ndarray4, return_index = True)

(array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32),
 array([ 5, 10,  0,  1,  6,  3, 17,  4,  2]))

In [28]:
# Find the 0'th index of the latest array you created
random_ndarray4[0]

array([3, 4, 9, 6, 8, 1, 5], dtype=int32)

In [29]:
# Get the first 2 rows of latest array you created
random_ndarray4[:2]

array([[3, 4, 9, 6, 8, 1, 5],
       [8, 1, 1, 2, 6, 1, 5]], dtype=int32)

In [44]:
# Get the first 2 values of the first 2 rows of the latest array
random_ndarray4[:2, :2]

array([[3, 4],
       [8, 1]], dtype=int32)

In [51]:
# Create a random array of numbers between 0 & 10 and an array of ones
# both of size (3, 5), save them both to variables
random_ndarray5 = np.random.randint(0, 10, (3, 5))
ones2 = np.ones(shape = (3, 5), dtype = "int")
random_ndarray5, ones2

(array([[7, 1, 2, 0, 7],
        [4, 8, 8, 6, 3],
        [6, 7, 4, 7, 8]], dtype=int32),
 array([[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]]))

In [52]:
# Add the two arrays together
random_ndarray5 + ones2

array([[8, 2, 3, 1, 8],
       [5, 9, 9, 7, 4],
       [7, 8, 5, 8, 9]])

In [54]:
# Create another array of ones of shape (5, 3)
ones3 = np.ones((5, 3), dtype = "int")
ones3

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [56]:
# Try add the array of ones and the other most recent array together
random_ndarray5 + ones3

ValueError: operands could not be broadcast together with shapes (3,5) (5,3) 

In [57]:
random_ndarray5

array([[7, 1, 2, 0, 7],
       [4, 8, 8, 6, 3],
       [6, 7, 4, 7, 8]], dtype=int32)

In [59]:
ones3.T

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

When you try the last cell, it produces an error. Why do think this is?

How would you fix it?

In [61]:
# Create another array of ones of shape (3, 5)
ones4 = np.ones((3, 5), dtype = "int")
ones4

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [62]:
# Subtract the new array of ones from the other most recent array
random_ndarray5 - ones4

array([[ 6,  0,  1, -1,  6],
       [ 3,  7,  7,  5,  2],
       [ 5,  6,  3,  6,  7]])

In [63]:
# Multiply the ones array with the latest array
random_ndarray5 * ones4

array([[7, 1, 2, 0, 7],
       [4, 8, 8, 6, 3],
       [6, 7, 4, 7, 8]])

In [73]:
# Take the latest array to the power of 2 using '**'
%timeit random_ndarray5 ** 2

759 ns ± 20.8 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [74]:
# Do the same thing with np.square()
%timeit np.square(random_ndarray5)

651 ns ± 25.6 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [75]:
# Find the mean of the latest array using np.mean()
np.mean(random_ndarray5)

np.float64(5.2)

In [77]:
random_ndarray5

array([[7, 1, 2, 0, 7],
       [4, 8, 8, 6, 3],
       [6, 7, 4, 7, 8]], dtype=int32)

In [78]:
# Find the maximum of the latest array using np.max()
np.max(random_ndarray5)

np.int32(8)

In [79]:
# Find the minimum of the latest array using np.min()
np.min(random_ndarray5)

np.int32(0)

In [80]:
# Find the standard deviation of the latest array
np.std(random_ndarray5)

np.float64(2.5871477215909673)

In [81]:
# Find the variance of the latest array
np.var(random_ndarray5)

np.float64(6.6933333333333325)

In [82]:
np.square(np.std(random_ndarray5))

np.float64(6.693333333333333)

In [83]:
random_ndarray5, random_ndarray5.shape

(array([[7, 1, 2, 0, 7],
        [4, 8, 8, 6, 3],
        [6, 7, 4, 7, 8]], dtype=int32),
 (3, 5))

In [84]:
# Reshape the latest array to (3, 5, 1)
random_ndarray5.reshape((3, 5, 1))

array([[[7],
        [1],
        [2],
        [0],
        [7]],

       [[4],
        [8],
        [8],
        [6],
        [3]],

       [[6],
        [7],
        [4],
        [7],
        [8]]], dtype=int32)

In [85]:
random_ndarray5

array([[7, 1, 2, 0, 7],
       [4, 8, 8, 6, 3],
       [6, 7, 4, 7, 8]], dtype=int32)

In [86]:
# Transpose the latest array
random_ndarray5.T

array([[7, 4, 6],
       [1, 8, 7],
       [2, 8, 4],
       [0, 6, 7],
       [7, 3, 8]], dtype=int32)

What does the transpose do?

In [89]:
# Create two arrays of random integers between 0 to 10
# one of size (3, 3) the other of size (3, 2)
random1 = np.random.randint(0, 10, (3, 3))
random2 = np.random.randint(0, 10, (3, 2))
random1, random2

(array([[1, 1, 9],
        [4, 8, 0],
        [6, 6, 6]], dtype=int32),
 array([[8, 6],
        [9, 5],
        [2, 2]], dtype=int32))

In [90]:
# Perform a dot product on the two newest arrays you created
random1.dot(random2)

array([[ 35,  29],
       [104,  64],
       [114,  78]], dtype=int32)

In [91]:
# Create two arrays of random integers between 0 to 10
# both of size (4, 3)
random3 = np.random.randint(0, 10, (4, 3))
random4 = np.random.randint(0, 10, (4, 3))
random3, random4

(array([[2, 7, 8],
        [6, 3, 7],
        [9, 1, 7],
        [7, 0, 3]], dtype=int32),
 array([[3, 9, 8],
        [8, 1, 8],
        [5, 8, 8],
        [0, 1, 0]], dtype=int32))

In [92]:
# Perform a dot product on the two newest arrays you created
random3.dot(random4)

ValueError: shapes (4,3) and (4,3) not aligned: 3 (dim 1) != 4 (dim 0)

In [95]:
reshaped_random3 = np.reshape(random3, (4, 3, 1))

In [98]:
random3, reshaped_random3.shape

(array([[2, 7, 8],
        [6, 3, 7],
        [9, 1, 7],
        [7, 0, 3]], dtype=int32),
 (4, 3, 1))

In [99]:
reshaped_random3.dot(random4)

ValueError: shapes (4,3,1) and (4,3) not aligned: 1 (dim 2) != 4 (dim 0)

It doesn't work. How would you fix it?

In [100]:
# Take the latest two arrays, perform a transpose on one of them and then perform 
# a dot product on them both
random3.dot(random4.T)

array([[133,  87, 130,   7],
       [101, 107, 110,   3],
       [ 92, 129, 109,   1],
       [ 45,  80,  59,   0]], dtype=int32)

Notice how performing a transpose allows the dot product to happen.

Why is this?

Checking out the documentation on [`np.dot()`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.dot.html) may help, as well as reading [Math is Fun's guide on the dot product](https://www.mathsisfun.com/algebra/vectors-dot-product.html).

Let's now compare arrays.

In [120]:
# Create two arrays of random integers between 0 & 10 of the same shape
# and save them to variables
random5 = np.random.randint(0, 10, (3, 6))
random6 = np.random.randint(0, 10, (3, 6))
random5, random6

(array([[1, 7, 9, 7, 6, 6],
        [2, 7, 4, 7, 9, 0],
        [2, 4, 5, 9, 9, 5]], dtype=int32),
 array([[6, 0, 7, 2, 7, 4],
        [4, 8, 3, 6, 7, 2],
        [9, 5, 5, 4, 7, 1]], dtype=int32))

In [121]:
# Compare the two arrays with '>'
random5 > random6

array([[False,  True,  True,  True, False,  True],
       [False, False,  True,  True,  True, False],
       [False, False, False,  True,  True,  True]])

What happens when you compare the arrays with `>`?

In [122]:
# Compare the two arrays with '>='
random5 >= random6

array([[False,  True,  True,  True, False,  True],
       [False, False,  True,  True,  True, False],
       [False, False,  True,  True,  True,  True]])

In [123]:
# Find which elements of the first array are greater than 7
random5 > 7

array([[False, False,  True, False, False, False],
       [False, False, False, False,  True, False],
       [False, False, False,  True,  True, False]])

In [124]:
# Which parts of each array are equal? (try using '==')
random5 == random6

array([[False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False,  True, False, False, False]])

In [131]:
random5

array([[1, 6, 6, 7, 7, 9],
       [0, 2, 4, 7, 7, 9],
       [2, 4, 5, 5, 9, 9]], dtype=int32)

In [132]:
# Sort one of the arrays you just created in ascending order
random5.sort()
random5

array([[1, 6, 6, 7, 7, 9],
       [0, 2, 4, 7, 7, 9],
       [2, 4, 5, 5, 9, 9]], dtype=int32)

In [138]:
random6

array([[6, 0, 7, 2, 7, 4],
       [4, 8, 3, 6, 7, 2],
       [9, 5, 5, 4, 7, 1]], dtype=int32)

In [137]:
# Sort the indexes of one of the arrays you just created
random6.argsort()

array([[1, 3, 5, 0, 2, 4],
       [5, 2, 0, 3, 4, 1],
       [5, 3, 2, 1, 4, 0]])

In [139]:
random3

array([[2, 7, 8],
       [6, 3, 7],
       [9, 1, 7],
       [7, 0, 3]], dtype=int32)

In [140]:
# Find the index with the maximum value in one of the arrays you've created
random3.argmax()

np.int64(6)

In [141]:
# Find the index with the minimum value in one of the arrays you've created
random3.argmin(axis = 0)

array([0, 3, 3])

In [142]:
random2

array([[8, 6],
       [9, 5],
       [2, 2]], dtype=int32)

In [143]:
# Find the indexes with the maximum values down the 1st axis (axis=1)
# of one of the arrays you created
random2.argmax(axis = 1)

array([0, 0, 0])

In [147]:
# Find the indexes with the minimum values across the 0th axis (axis=0)
# of one of the arrays you created
random2.argmax(axis = 0)

array([1, 0])

In [148]:
random2.argmin(axis = 0)

array([2, 2])

In [160]:
# Create an array of normally distributed random numbers
ndarray = np.random.randn(2, 4)
ndarray

array([[-0.66445979, -0.26065682,  0.97914256, -0.52909831],
       [-0.90913479, -1.33085227,  0.3725082 , -1.86828789]])

In [162]:
# Create an array with 10 evenly spaced numbers between 1 and 100
ndarray = np.arange(1, 100, 11)
ndarray

array([ 1, 12, 23, 34, 45, 56, 67, 78, 89])

## Extensions

For more exercises, check out the [NumPy quickstart tutorial](https://numpy.org/doc/stable/user/quickstart.html). A good practice would be to read through it and for the parts you find interesting, add them into the end of this notebook.

Pay particular attention to the section on broadcasting. And most importantly, get hands-on with the code as much as possible. If in dobut, run the code, see what it does.

The next place you could go is the [Stack Overflow page for the top questions and answers for NumPy](https://stackoverflow.com/questions/tagged/numpy?sort=MostVotes&edited=true). Often, you'll find some of the most common and useful NumPy functions here. Don't forget to play around with the filters! You'll likely find something helpful here.

Finally, as always, remember, the best way to learn something new is to try it. And try it relentlessly. If you get interested in some kind of NumPy function, asking yourself, "I wonder if NumPy could do that?", go and find out.