# NumPy DataTypes & Attributes

In [1]:
import numpy as np

In [3]:
# NumPy's main dataype is ndarray

In [6]:
a1 = np.array([1, 2, 3])
a1

array([1, 2, 3])

In [7]:
type(a1)

numpy.ndarray

In [14]:
a2 = np.array([[1,2,3], [4,5,6]])
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [15]:
a3 = np.array([
               [[1,2,3], [3,4,5]], 
               [[5,6,7], [7,8,9]],
               [[9,10,11],[11,12,13]]
              ])
a3

array([[[ 1,  2,  3],
        [ 3,  4,  5]],

       [[ 5,  6,  7],
        [ 7,  8,  9]],

       [[ 9, 10, 11],
        [11, 12, 13]]])

In [17]:
a1.dtype, a2.dtype, a3.dtype

(dtype('int64'), dtype('int64'), dtype('int64'))

In [18]:
type(a3)

numpy.ndarray

In [20]:
a1.size, a2.size, a3.size

(3, 6, 18)

In [23]:
a1.shape, a2.shape, a3.shape

((3,), (2, 3), (3, 2, 3))

In [24]:
import pandas as pd

In [26]:
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [28]:
pd.DataFrame({"Make":["BMW", "Audi", "Opel"], "Colour":["Red", "Blue", "Black"]})

,Make,Colour
0,BMW,Red
1,Audi,Blue
2,Opel,Black


In [33]:
df = pd.DataFrame(columns=["A", "B"], data=[[1,2]])
df

,A,B
0,1,2


In [35]:
dataframe = pd.DataFrame(a2)
dataframe

,0,1,2
0,1,2,3
1,4,5,6


In [36]:
df2 = pd.DataFrame(a3)
df2

ValueError: Must pass 2-d input. shape=(3, 2, 3)