In [4]:
import pandas as pd
import numpy as np
%matplotlib inline
import matplotlib.pylab as plt

In [10]:
rng = np.random.default_rng(0)
a2 = rng.integers(0, 100, size=(2, 3))
a2

array([[85, 63, 51],
       [26, 30,  4]])

In [11]:
rng2 = np.random.default_rng(0)
a3 = rng.integers(0, 100, size=(2, 3, 3))
a3

array([[[ 7,  1, 17],
        [81, 64, 91],
        [50, 60, 97]],

       [[72, 63, 54],
        [55, 93, 27],
        [81, 67,  0]]])

In [12]:
a2 * a3

ValueError: operands could not be broadcast together with shapes (2,3) (2,3,3) 

In [21]:
# Resize
resized_a2 = np.resize(a2, (3, 3)) 
resized_a2

array([[85, 63, 51],
       [26, 30,  4],
       [85, 63, 51]])

In [22]:
resized_a2 * a3

array([[[ 595,   63,  867],
        [2106, 1920,  364],
        [4250, 3780, 4947]],

       [[6120, 3969, 2754],
        [1430, 2790,  108],
        [6885, 4221,    0]]])

In [24]:
# Reshape
reshaped_a2 = np.reshape(a2, (2,3,1))

In [25]:
reshaped_a2

array([[[85],
        [63],
        [51]],

       [[26],
        [30],
        [ 4]]])

In [34]:
a3

array([[[ 7,  1, 17],
        [81, 64, 91],
        [50, 60, 97]],

       [[72, 63, 54],
        [55, 93, 27],
        [81, 67,  0]]])

In [35]:
reshaped_a2 * a3

array([[[ 595,   85, 1445],
        [5103, 4032, 5733],
        [2550, 3060, 4947]],

       [[1872, 1638, 1404],
        [1650, 2790,  810],
        [ 324,  268,    0]]])

In [36]:
# Transpose
a3.T.shape

(3, 3, 2)

In [37]:
a2.shape

(2, 3)

In [38]:
a2.T.shape

(3, 2)