In [1]:
import numpy as np
import pandas as pd
%matplotlib inline
import matplotlib.pyplot as plt

In [3]:
a1 = np.array([1, 2, 3])
a1

array([1, 2, 3])

In [10]:
rng = np.random.default_rng(0)
a2 = rng.random(size = (2, 3))
a2

array([[0.63696169, 0.26978671, 0.04097352],
       [0.01652764, 0.81327024, 0.91275558]])

In [21]:
a3 = np.random.uniform(low = 10.5, high = 3.5, size=(2,3,4))
a3

array([[[ 4.59648754,  6.6654624 ,  6.60835216,  6.14454798],
        [ 5.91694784,  5.40325331,  9.86123744,  7.51598566],
        [10.02277496,  3.89346882,  8.42248363,  5.9336505 ]],

       [[ 7.16301503,  4.44164633,  6.25791338,  6.79007196],
        [ 4.25496558,  7.52324821,  3.95609716,  6.87451111],
        [ 8.53810911,  3.81690187,  8.34991996,  5.51306102]]])

In [30]:
a4 = np.random.randint(1, 5, (2, 3, 3, 3, 5))
a4

array([[[[[4, 4, 3, 3, 1],
          [2, 4, 3, 1, 1],
          [2, 2, 3, 3, 4]],

         [[1, 1, 4, 1, 3],
          [1, 4, 4, 1, 1],
          [1, 4, 4, 1, 3]],

         [[4, 3, 1, 2, 2],
          [3, 2, 4, 1, 2],
          [2, 4, 3, 1, 1]]],


        [[[3, 1, 3, 3, 4],
          [4, 4, 3, 4, 1],
          [1, 2, 2, 4, 4]],

         [[4, 1, 4, 4, 4],
          [2, 4, 2, 4, 4],
          [4, 3, 2, 2, 4]],

         [[1, 2, 3, 2, 1],
          [2, 4, 1, 2, 4],
          [1, 2, 2, 3, 1]]],


        [[[1, 2, 4, 1, 3],
          [2, 2, 3, 2, 3],
          [1, 3, 1, 1, 4]],

         [[3, 1, 1, 4, 3],
          [3, 3, 3, 3, 4],
          [4, 3, 1, 1, 3]],

         [[4, 1, 3, 3, 3],
          [2, 2, 3, 3, 4],
          [2, 2, 3, 4, 3]]]],



       [[[[2, 2, 2, 4, 4],
          [1, 1, 1, 4, 3],
          [1, 1, 3, 3, 3]],

         [[4, 2, 1, 3, 3],
          [3, 2, 3, 1, 3],
          [4, 1, 3, 1, 1]],

         [[1, 3, 1, 2, 2],
          [3, 4, 2, 1, 3],
          [2, 2, 3, 2, 3]

In [31]:
a4.dtype

dtype('int32')

In [32]:
a4.shape

(2, 3, 3, 3, 5)

In [33]:
a4[1][2][1][2]

array([4, 1, 1, 1, 2], dtype=int32)

In [50]:
# unique method
unique_numbers = np.unique(a4, return_counts = True)
unique_numbers

(array([1, 2, 3, 4], dtype=int32), array([68, 68, 75, 59]))

In [51]:
a2 = np.random.randint(0, 10, (2,3))
a2

array([[9, 5, 7],
       [3, 0, 7]], dtype=int32)

In [52]:
unique_numbers = np.unique(a2, return_counts = True)
unique_numbers

(array([0, 3, 5, 7, 9], dtype=int32), array([1, 1, 1, 2, 1]))

In [53]:
a4

array([[[[[4, 4, 3, 3, 1],
          [2, 4, 3, 1, 1],
          [2, 2, 3, 3, 4]],

         [[1, 1, 4, 1, 3],
          [1, 4, 4, 1, 1],
          [1, 4, 4, 1, 3]],

         [[4, 3, 1, 2, 2],
          [3, 2, 4, 1, 2],
          [2, 4, 3, 1, 1]]],


        [[[3, 1, 3, 3, 4],
          [4, 4, 3, 4, 1],
          [1, 2, 2, 4, 4]],

         [[4, 1, 4, 4, 4],
          [2, 4, 2, 4, 4],
          [4, 3, 2, 2, 4]],

         [[1, 2, 3, 2, 1],
          [2, 4, 1, 2, 4],
          [1, 2, 2, 3, 1]]],


        [[[1, 2, 4, 1, 3],
          [2, 2, 3, 2, 3],
          [1, 3, 1, 1, 4]],

         [[3, 1, 1, 4, 3],
          [3, 3, 3, 3, 4],
          [4, 3, 1, 1, 3]],

         [[4, 1, 3, 3, 3],
          [2, 2, 3, 3, 4],
          [2, 2, 3, 4, 3]]]],



       [[[[2, 2, 2, 4, 4],
          [1, 1, 1, 4, 3],
          [1, 1, 3, 3, 3]],

         [[4, 2, 1, 3, 3],
          [3, 2, 3, 1, 3],
          [4, 1, 3, 1, 1]],

         [[1, 3, 1, 2, 2],
          [3, 4, 2, 1, 3],
          [2, 2, 3, 2, 3]

In [57]:
a4.shape, a4.ndim

((2, 3, 3, 3, 5), 5)

In [63]:
a2[:, :2]

array([[9, 5],
       [3, 0]], dtype=int32)

In [65]:
a4[:,:,:,:,:1]

array([[[[[4],
          [2],
          [2]],

         [[1],
          [1],
          [1]],

         [[4],
          [3],
          [2]]],


        [[[3],
          [4],
          [1]],

         [[4],
          [2],
          [4]],

         [[1],
          [2],
          [1]]],


        [[[1],
          [2],
          [1]],

         [[3],
          [3],
          [4]],

         [[4],
          [2],
          [2]]]],



       [[[[2],
          [1],
          [1]],

         [[4],
          [3],
          [4]],

         [[1],
          [3],
          [2]]],


        [[[3],
          [4],
          [1]],

         [[2],
          [2],
          [4]],

         [[2],
          [4],
          [1]]],


        [[[2],
          [3],
          [2]],

         [[2],
          [2],
          [4]],

         [[2],
          [2],
          [4]]]]], dtype=int32)